[package]
name = "gba_test_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = {version = "2.0.15", features = ["full"]}

[dev-dependencies]
trybuild = "1.0.80"
