name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pwd
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2023-03-24
        components: rust-src
    - run: rustup target add thumbv4t-none-eabi --toolchain nightly-2023-03-24
    - run: sudo apt-get update
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: sudo apt-get install mgba-qt
    - run: alias mgba="mgba-qt"
    - run: curl -LsSf https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin
    # - run: cargo hack test --feature-powerset
    - run: cargo test --all-features --workspace
