name: gba_test

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: cd gba_test && cargo test --no-run --message-format=json | tee results.json
    - run: echo "ROM_PATH=$(cd tests/parse_executable && cargo run ../../gba_test/results.json )" >> $GITHUB_ENV
    - run: arm-none-eabi-objcopy -O binary ${{ env.ROM_PATH }} test.gba
    - run: cargo install gbafix
    - run: gbafix test.gba
    - uses: felixjones/github-mgba-rom-test@v1
      with:
        swi-call: 0x27
        read-register: 'r0'
        rom-path: test.gba
        success-code: 0  # Pass

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - run: cd gba_test && cargo check

  # clippy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: dtolnay/rust-toolchain@nightly
  #     with:
  #       components: clippy
  #   - run: cd gba_test && cargo clippy -- --deny warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - run: cd gba_test && cargo fmt -- --check
