name: mgba-rom-test

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  pass:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: cd tests/pass && cargo test --no-run --message-format=json | tee results.json
    - run: echo "ROM_PATH=$(cd tests/parse_executable && cargo run ../pass/results.json)" >> $GITHUB_ENV
    - run: arm-none-eabi-objcopy -O binary ${{ env.ROM_PATH }} pass.gba
    - run: cargo install gbafix
    - run: gbafix pass.gba
    - uses: felixjones/github-mgba-rom-test@v1
      with:
        swi-call: 0x27
        read-register: 'r0'
        rom-path: pass.gba
        success-code: 0  # Pass

  ignore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: cd tests/ignore && cargo test --no-run --message-format=json | tee results.json
    - run: echo "ROM_PATH=$(cd tests/parse_executable && cargo run ../ignore/results.json)" >> $GITHUB_ENV
    - run: arm-none-eabi-objcopy -O binary ${{ env.ROM_PATH }} ignore.gba
    - run: cargo install gbafix
    - run: gbafix ignore.gba
    - uses: felixjones/github-mgba-rom-test@v1
      with:
        swi-call: 0x27
        read-register: 'r0'
        rom-path: ignore.gba
        success-code: 0  # Pass

  ignore_with_message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: cd tests/ignore_with_message && cargo test --no-run --message-format=json | tee results.json
    - run: echo "ROM_PATH=$(cd tests/parse_executable && cargo run ../ignore_with_message/results.json)" >> $GITHUB_ENV
    - run: arm-none-eabi-objcopy -O binary ${{ env.ROM_PATH }} ignore_with_message.gba
    - run: cargo install gbafix
    - run: gbafix ignore_with_message.gba
    - uses: felixjones/github-mgba-rom-test@v1
      with:
        swi-call: 0x27
        read-register: 'r0'
        rom-path: ignore_with_message.gba
        success-code: 0  # Pass

  multiple_ignore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: cd tests/multiple_ignore && cargo test --no-run --message-format=json | tee results.json
    - run: echo "ROM_PATH=$(cd tests/parse_executable && cargo run ../multiple_ignore/results.json)" >> $GITHUB_ENV
    - run: arm-none-eabi-objcopy -O binary ${{ env.ROM_PATH }} multiple_ignore.gba
    - run: cargo install gbafix
    - run: gbafix multiple_ignore.gba
    - uses: felixjones/github-mgba-rom-test@v1
      with:
        swi-call: 0x27
        read-register: 'r0'
        rom-path: multiple_ignore.gba
        success-code: 0  # Pass

  fail:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: cd tests/fail && cargo test --no-run --message-format=json | tee results.json
    - run: echo "ROM_PATH=$(cd tests/parse_executable && cargo run ../fail/results.json)" >> $GITHUB_ENV
    - run: arm-none-eabi-objcopy -O binary ${{ env.ROM_PATH }} fail.gba
    - run: cargo install gbafix
    - run: gbafix fail.gba
    - uses: felixjones/github-mgba-rom-test@v1
      with:
        swi-call: 0x27
        read-register: 'r0'
        rom-path: fail.gba
        success-code: 1  # Fail

  should_panic_pass:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: cd tests/should_panic_pass && cargo test --no-run --message-format=json | tee results.json
    - run: echo "ROM_PATH=$(cd tests/parse_executable && cargo run ../should_panic_pass/results.json)" >> $GITHUB_ENV
    - run: arm-none-eabi-objcopy -O binary ${{ env.ROM_PATH }} should_panic_pass.gba
    - run: cargo install gbafix
    - run: gbafix should_panic_pass.gba
    - uses: felixjones/github-mgba-rom-test@v1
      with:
        swi-call: 0x27
        read-register: 'r0'
        rom-path: should_panic_pass.gba
        success-code: 0  # Pass

  should_panic_fail:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: cd tests/should_panic_fail && cargo test --no-run --message-format=json | tee results.json
    - run: echo "ROM_PATH=$(cd tests/parse_executable && cargo run ../should_panic_fail/results.json)" >> $GITHUB_ENV
    - run: arm-none-eabi-objcopy -O binary ${{ env.ROM_PATH }} should_panic_fail.gba
    - run: cargo install gbafix
    - run: gbafix should_panic_fail.gba
    - uses: felixjones/github-mgba-rom-test@v1
      with:
        swi-call: 0x27
        read-register: 'r0'
        rom-path: should_panic_fail.gba
        success-code: 1  # Fail

  allocate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: cd tests/allocate && cargo test --no-run --message-format=json | tee results.json
    - run: echo "ROM_PATH=$(cd tests/parse_executable && cargo run ../allocate/results.json)" >> $GITHUB_ENV
    - run: arm-none-eabi-objcopy -O binary ${{ env.ROM_PATH }} allocate.gba
    - run: cargo install gbafix
    - run: gbafix allocate.gba
    - uses: felixjones/github-mgba-rom-test@v1
      with:
        swi-call: 0x27
        read-register: 'r0'
        rom-path: allocate.gba
        success-code: 0  # Pass

  result_pass:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: cd tests/result_pass && cargo test --no-run --message-format=json | tee results.json
    - run: echo "ROM_PATH=$(cd tests/parse_executable && cargo run ../result_pass/results.json)" >> $GITHUB_ENV
    - run: arm-none-eabi-objcopy -O binary ${{ env.ROM_PATH }} result_pass.gba
    - run: cargo install gbafix
    - run: gbafix result_pass.gba
    - uses: felixjones/github-mgba-rom-test@v1
      with:
        swi-call: 0x27
        read-register: 'r0'
        rom-path: result_pass.gba
        success-code: 0  # Pass

  result_fail:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: cd tests/result_fail && cargo test --no-run --message-format=json | tee results.json
    - run: echo "ROM_PATH=$(cd tests/parse_executable && cargo run ../result_fail/results.json)" >> $GITHUB_ENV
    - run: arm-none-eabi-objcopy -O binary ${{ env.ROM_PATH }} result_fail.gba
    - run: cargo install gbafix
    - run: gbafix result_fail.gba
    - uses: felixjones/github-mgba-rom-test@v1
      with:
        swi-call: 0x27
        read-register: 'r0'
        rom-path: result_fail.gba
        success-code: 1  # Fail
