name: mgba-rom-test

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  pass:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    # Build mGBA ROM test
    - run: mkdir mgba
    - run: curl -LsSf https://github.com/mgba-emu/mgba/archive/refs/tags/0.10.3.tar.gz | tar xzf - -C mgba
    - run: cd mgba/mgba-0.10.3 && mkdir build && cd build && cmake -DUSE_LIBZIP=OFF -DBUILD_ROM_TEST=ON -DUSE_PNG=OFF .. && make
    - run: cd tests/pass && cargo test
    # - uses: felixjones/github-mgba-rom-test@v1
    #   with:
    #     swi-call: 0x27
    #     read-register: 'r0'
    #     rom-path: ''
    #     success-code: 0  # Pass
